### ISSUE TITLE
Cannot separate sabers in darth maul mode

### ISSUE THREAD

**Issue by Saroquen** [Kylon99/AlternativePlay#2]
I tried pressing both triggers in one and two-handed mode but nothing happened (trigger option was enabled). Tested on Vive and Index controllers. Triggers work fine in menus, just no effect in-game.

**Comment by Kylon99** [comment]
Are you using DynamicOpenVR?  It seems to interfere with the triggers I think.  I'm not sure how as I don't use it.  I've had problems where it would prevent my triggers from working in Beat Saber even though I uninstalled it and had to use its troubleshooting instructions to remove its binding from the SteamVR config file directly.

**Comment by Saroquen** [comment]
I think I'm using DynamicOpenVR for the Avatars mod. I'll try removing both and see if it works.

**Comment by Kylon99** [comment]
It might be possible to rebind the trigger function in SteamVR to another button?  Or maybe there's some other way to get around DynamicOpenVR as it seems to want to take over the trigger.

**Comment by Saroquen** [comment]
As you said, DynamicOpenVR was causing the issue. I've seen people with avatars using this mod though, so I'll try your suggestion on rebinding that trigger. On the Vive controllers especially, I kept brushing against the trigger in maul mode and going back to dual.

On another note, I am using one-handed mode since it is easier to control the maul saber that way, but I noticed that vibrations on the other controller are then turned off. Is there any way to turn them back on when the sabers are in dual mode?

**Comment by Kylon99** [comment]
Yeah, unfortunately the triggers are really sensitive.  Unity reports the trigger press to me and I'm not sure what else I can do with it as I'm not in control.  I prefer the two trigger press of the two controller mode but I had to keep it to one trigger in case people are using a tracker or something.  I wanted to implement allowing people to choose a button but the UI for that will take a very long time... (there's no UI already built for this at all, nevermind the proper enumeration of the buttons of the Index)

As for the vibrations when you split, I will be finding some time to fix that soon.  That should be an easy fix, I think.

**Comment by Kylon99** [comment]
0.2.3 has been released which fixes the vibrations when splitting in Darth Maul.  I'll close this for now as the trigger issue will take a long time to fix, by basically introducing a new feature to get around it.  Maybe.
