### ISSUE TITLE
Mod not showing up due to missing AlternativePlay.dll

### ISSUE THREAD

**Issue by Cimbro94** [Kylon99/AlternativePlay#26]
![image](https://user-images.githubusercontent.com/84040952/117868342-c92f6900-b299-11eb-9aec-ef30d681c3fb.png)
![image](https://user-images.githubusercontent.com/84040952/117868398-db110c00-b299-11eb-9c5f-b75179c6cfb8.png)
Basically in the *.zip file there's no dll file to make the mod work....

**Comment by Kylon99** [comment]
It looks like you just downloaded the source code and not the actual release.
You need to get the zip file with the release from here.
https://github.com/Kylon99/AlternativePlay/releases/download/0.6.1/AlternativePlay_0.6.1_1.14.zip
