### ISSUE TITLE
Not there

### ISSUE THREAD

**Issue by SliceeGamer** [Kylon99/AlternativePlay#3]
Hi, i played on beat saber 1.8.0b1 and downloaded the mod and it isnt there, can you help? the mod version i downloaded is 2.3.0

**Comment by Kylon99** [comment]
Hello, version 0.2.3 is only compatible with 1.6.0 to 1.7.0 of Beat Saber for now.  I haven't had any time to get it updated to 1.8.0 yet and it's still in beta.
