### ISSUE TITLE
Release for 0.5.0?

### ISSUE THREAD

**Issue by monkalynn813** [Kylon99/AlternativePlay#5]
Hi, Firstly thank you for creating this great mod for the community.
I am wondering if 0.5.0 is not released as .dll, how we would like to install the newest version? Thanks

**Comment by Kylon99** [comment]
You can use Snow's version here:
https://github.com/Snow1226/AlternativePlay/releases/tag/0.5.1

It's compatible with Beat Saber 1.12 and 1.13.  I've merged in the code from there but haven't made any further changes yet.

**Comment by monkalynn813** [comment]
It works, thank you
