### ISSUE TITLE
Pre-build

### ISSUE THREAD

**Issue by lusokol** [Kylon99/AlternativePlay#54]
Hi guys,
Your project is insane ! I love it :D
Just one thing, you should prebuild into .dll, because a lot of people will not understand how doing it.
And maybe add a link to something like google drive or I don't know into your readme to download directly the .dll
That's all ! Thank you again,
Bye !
Lucas S.

**Comment by Kylon99** [comment]
Yup!  I make a build and publish it in the Releases on this github instance.  If you go to
https://github.com/Kylon99/AlternativePlay/releases

You can see the latest release there.  The zip file (for this example https://github.com/Kylon99/AlternativePlay/releases/download/0.7.4/AlternativePlay_0.7.4_for_1.21_D5A07BE6.zip ) has the DLL in it.
